on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]
    branches:
      - master

name: release

jobs:
  publish:
    name: npm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install --only=prod
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: ${{ github.event_name != 'release'  || github.ref != 'refs/heads/master' }}
